#!/usr/bin/env python3
"""
Setup script to help create a .env file for the Orbit Bhyve package.
"""

import os
import getpass


def main():
    """Create a .env file with user credentials."""
    print("Orbit Bhyve .env Setup")
    print("=" * 30)
    print()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        response = input(".env file already exists. Overwrite? (y/N): ")
        if response.lower() not in ['y', 'yes']:
            print("Setup cancelled.")
            return
    
    print("Enter your Orbit Bhyve credentials:")
    print()
    
    # Get username
    username = input("Username/Email: ").strip()
    if not username:
        print("Username is required!")
        return
    
    # Get password
    password = getpass.getpass("Password: ")
    if not password:
        print("Password is required!")
        return
    
    # Optional token
    print()
    print("Optional: Pre-obtained token (press Enter to skip):")
    token = input("Token: ").strip()
    
    # Create .env file
    env_content = f"""# Orbit Bhyve API Credentials
# Generated by setup_env.py

BHYVE_USERNAME={username}
BHYVE_PASSWORD={password}
"""
    
    if token:
        env_content += f"BHYVE_TOKEN={token}\n"
    
    env_content += """
# Optional settings (uncomment and modify as needed)
# BHYVE_BASE_URL=https://api.orbitbhyve.com/v1
# BHYVE_TIMEOUT=30
# BHYVE_RETRY_ATTEMPTS=3
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print()
        print("✅ .env file created successfully!")
        print()
        print("You can now run the example scripts:")
        print("  python examples/basic_usage.py")
        print("  python examples/smart_watering.py")
        print("  python examples/config_example.py")
        print()
        print("Or use the command-line interface:")
        print("  orbit-bhyve list-devices")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")


if __name__ == '__main__':
    main()
